// Generated by CoffeeScript 1.7.1
(function() {
  var chai, expect, sinon, sinonChai;

  sinon = require('sinon');

  chai = require('chai');

  expect = chai.expect;

  sinonChai = require('sinon-chai');

  chai.use(sinonChai);

  global.sinon = sinon;

  global.expect = expect;

}).call(this);
