// Generated by CoffeeScript 1.7.1
(function() {
  var PeerStore;

  PeerStore = (function() {
    PeerStore.prototype.callbacks = {};

    PeerStore.prototype.peers = [];

    function PeerStore(options) {
      var _ref;
      this.options = options;
      this.URL = ((_ref = this.options) != null ? _ref.URL : void 0) || global.URL;
    }

    PeerStore.prototype.add = function(peer) {
      this.peers.push(peer);
      return this.trigger('add', peer);
    };

    PeerStore.prototype.addStream = function(peerId, stream) {
      var peer;
      peer = void 0;
      this.peers.forEach(function(p) {
        if (p.peerId === peerId) {
          return peer = p;
        }
      });
      peer.stream = stream;
      peer.streamUrl = this.URL.createObjectURL(stream);
      return this.trigger('streamAdded', peer);
    };

    PeerStore.prototype.remove = function(peerId) {
      var peers, removedPeer;
      removedPeer = void 0;
      peers = [];
      this.peers.forEach(function(peer) {
        if (peer.peerId === peerId) {
          return removedPeer = peer;
        } else {
          return peers.push(peer);
        }
      });
      this.peers = peers;
      return this.trigger('remove', removedPeer);
    };

    PeerStore.prototype.find = function(peerId) {
      var peer;
      peer = void 0;
      this.peers.forEach(function(p) {
        if (p.peerId === peerId) {
          return peer = p;
        }
      });
      return peer;
    };

    PeerStore.prototype.peersWithStreams = function() {
      var peersWithStreams;
      peersWithStreams = [];
      this.peers.forEach((function(_this) {
        return function(peer) {
          if (_this._hasStream(peer)) {
            return peersWithStreams.push(peer);
          }
        };
      })(this));
      return peersWithStreams;
    };

    PeerStore.prototype.peersWithoutStreams = function() {
      var peersWithoutStreams;
      peersWithoutStreams = [];
      this.peers.forEach((function(_this) {
        return function(peer) {
          if (!_this._hasStream(peer)) {
            return peersWithoutStreams.push(peer);
          }
        };
      })(this));
      return peersWithoutStreams;
    };

    PeerStore.prototype.on = function(event, callback) {
      var _base;
      (_base = this.callbacks)[event] || (_base[event] = []);
      return this.callbacks[event].push(callback);
    };

    PeerStore.prototype.trigger = function(event) {
      var args, callbacks;
      args = Array.prototype.slice.call(arguments, 1);
      if (callbacks = this.callbacks[event]) {
        return callbacks.forEach(function(callback) {
          return callback.apply(this, args);
        });
      }
    };

    PeerStore.prototype._hasStream = function(peer) {
      return !!peer.stream;
    };

    return PeerStore;

  })();

  module.exports = PeerStore;

}).call(this);
